package yapl.impl;/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int RelOp = 8;
  /** RegularExpression Id. */
  int EqualOp = 9;
  /** RegularExpression Id. */
  int AddOp = 10;
  /** RegularExpression Id. */
  int MulOp = 11;
  /** RegularExpression Id. */
  int digit = 40;
  /** RegularExpression Id. */
  int letter = 41;
  /** RegularExpression Id. */
  int otherchar = 42;
  /** RegularExpression Id. */
  int ident = 43;
  /** RegularExpression Id. */
  int number = 44;
  /** RegularExpression Id. */
  int string = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<RelOp>",
    "<EqualOp>",
    "<AddOp>",
    "<MulOp>",
    "\"True\"",
    "\"False\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"And\"",
    "\"new\"",
    "\"Or\"",
    "\",\"",
    "\":=\"",
    "\"If\"",
    "\"Then\"",
    "\"Else\"",
    "\"EndIf\"",
    "\"While\"",
    "\"Do\"",
    "\"EndWhile\"",
    "\"Return\"",
    "\"Write\"",
    "\";\"",
    "\"Begin\"",
    "\"End\"",
    "\"int\"",
    "\"bool\"",
    "\"void\"",
    "<digit>",
    "<letter>",
    "<otherchar>",
    "<ident>",
    "<number>",
    "<string>",
  };

}
